CREATE IF NOT EXISTS TABLE Config (Name PRIMARY KEY VARCHAR(1024), Value NOT NULL VARCHAR(1024));

CREATE IF NOT EXISTS TABLE Log (id PRIMARY KEY, datetime TIMESTAMP, String NOT NULL VARCHAR(1024));

